In [106]:
#%load_ext autoreload
%autoreload 2
import numpy as np
import os
import collections

def load_20news(path="./20news-bydate"):
    
    # http://qwone.com/~jason/20Newsgroups/
    
    def read_dataset(name):
        
        print "loading the {} set".format(name)
        # load the data
        data = open(os.path.join(path, "matlab/{}.data".format(name))).read()
        data = data.split("\n")[:-1] # The last line is empty
        nb_lines = len(data)
        
        #make a np.array
        file_np = np.zeros((nb_lines, 3))
        for no, line in enumerate(data):
            
            try:
                line = [int(i) for i in line.split()]
                file_np[no] = np.array(line)
            except ValueError:
                pass
            
        M = len(set(file_np[:, 0]))
        docs = []
        for d in range(1, M+1):
            doc = file_np[np.where(file_np[:, 0] == d)]
            doc = doc[:, 1:].astype(int)# remove the doc id
            
            if d % 1000 == 0:
                print "Done loading {} documents".format(d)
                        
            doc_array = np.array(list(collections.Counter(dict(doc)).elements()))
            docs.append(doc_array)
            
        return docs
    
    def read_labels(name):
        print "loading the labels for {} set".format(name)
        labels = open(os.path.join(path, "matlab/{}.label".format(name))).read()
        labels = labels.split("\n")[:-1] # The last line is empty
        labels = np.array(labels).astype(int)
        return labels
        
        
        
    def load_map(name):
        print "loading the map for {} set".format(name)
        
        mapping = open(os.path.join(path, "matlab/{}.map".format(name))).read()
        mapping = mapping.split("\n")[:-1]
        
        mapping = [[int(line.split()[1]), line.split()[0]] for line in mapping]
        return dict(mapping)
        
    def load_vocabulary():
        
        print "loading the vocabulary"
        vocab = open(os.path.join(path, "vocabulary.txt")).read()
        vocab = vocab.split('\n')[:-1]
        return vocab
    
    train_data = read_dataset('train')
    train_labels = read_labels('train')
    train_map = load_map('train')
    
    test_data = read_dataset('test')
    test_labels = read_labels('test')
    test_map = load_map('test')
    
    vocab = load_vocabulary()
    
    return train_data, train_labels, train_map, test_data, test_labels, test_map, vocab

train_data, train_labels, train_map, test_data, test_labels, test_map, vocab = load_20news()

    

loading the train set
[[  29    1]
 [ 102    1]
 [ 122    1]
 [ 877    1]
 [ 912    1]
 [1036    1]
 [1932    1]
 [2379    1]
 [2479    1]
 [3695    1]
 [6217    1]
 [6321    1]
 [6531    1]
 [6864    1]
 [6865    1]]
[ 912 6531  102 6321 1036 2379 1932  877 2479 6864 6865 6217  122 3695   29]
loading the labels for train set
loading the map for train set
loading the test set
loading the labels for test set
loading the map for test set
loading the vocabulary


In [115]:
import vb_lda

vocabSize = len(vocab)
learned_alpha, learned_B, log_likes = vb_lda.Var_EM(20, vocabSize, train_data, maxIter=1, batchSize=-1)

vb_lda.py:25: RuntimeWarning: invalid value encountered in divide
  phis_tp1 /= phis_tp1.sum(axis=0)
vb_lda.py:170: RuntimeWarning: divide by zero encountered in log
  raise e
vb_lda.py:232: RuntimeWarning: invalid value encountered in absolute
  
vb_lda.py:109: RuntimeWarning: invalid value encountered in less_equal
  # print "hoho!"


The normalized log-likelyhood is: nan
Took to long to converge :S (101)
Done one interation in 52.4 seconds


In [85]:
train_map

{1: 'alt.atheism',
 2: 'comp.graphics',
 3: 'comp.os.ms-windows.misc',
 4: 'comp.sys.ibm.pc.hardware',
 5: 'comp.sys.mac.hardware',
 6: 'comp.windows.x',
 7: 'misc.forsale',
 8: 'rec.autos',
 9: 'rec.motorcycles',
 10: 'rec.sport.baseball',
 11: 'rec.sport.hockey',
 12: 'sci.crypt',
 13: 'sci.electronics',
 14: 'sci.med',
 15: 'sci.space',
 16: 'soc.religion.christian',
 17: 'talk.politics.guns',
 18: 'talk.politics.mideast',
 19: 'talk.politics.misc',
 20: 'talk.religion.misc'}

In [113]:
learned_alpha

array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan])

In [54]:
np.array(collections.Counter(dict(np.array([[1, 2],[3, 4]]))).elements())

array(<itertools.chain object at 0x7f3005e32290>, dtype=object)

In [83]:
dict([[1, '2'],[3, '4']])

{1: '2', 3: '4'}