In [143]:
#%load_ext autoreload
%autoreload 2
import dataset
import vb_lda
import numpy as np

nTopics = 3
vocabSize = 3
nDocs= 500
averageLength=1000
[[topicsDist, topicsOfDocs, wordsOfDocs], [real_alpha, real_B]] = dataset.generateRandomCorpus(nTopics=nTopics,
                                                                                               vocabSize=vocabSize,
                                                                                               nDocs=nDocs,
                                                                                               averageLength=averageLength)

In [ ]:
wordsOfDocs[0]

In [144]:
learned_alpha, learned_B, log_likes = vb_lda.Var_EM(nTopics, vocabSize, wordsOfDocs, maxIter=25, batchSize=-1)

The normalized log-likelyhood is: -0.00811857332408
Done one interation in 7.3 seconds
The normalized log-likelyhood is: -0.00801607397353
Done one interation in 6.6 seconds
The normalized log-likelyhood is: -0.0080585986726
Done one interation in 6.3 seconds
The normalized log-likelyhood is: -0.00809242874769
Done one interation in 6.3 seconds
The normalized log-likelyhood is: -0.00811991821876
Done one interation in 6.2 seconds
The normalized log-likelyhood is: -0.00812779733762
We converged!


In [145]:
print vb_lda.log_likelyhood(real_alpha, real_B, wordsOfDocs)

-0.00811682951773


In [146]:
np.argmax(learned_B, axis=1)

array([2, 1, 0])

In [147]:
np.argmax(real_B, axis=1)

array([1, 2, 0])

In [137]:
np.argsort(learned_B[-1])[::-1]

array([5, 1, 4, 6, 9, 0, 3, 8, 2, 7])

In [138]:
np.argsort(real_B[0])[::-1]

array([5, 1, 6, 9, 4, 7, 3, 8, 2, 0])

In [153]:
learned_B[1]

array([ 0.03393701,  0.92781239,  0.0382506 ])

In [152]:
real_B[0]

array([  5.94585399e-04,   9.94380612e-01,   5.02480290e-03])

In [415]:
learn_B[0]

array([ 0.64438657,  0.00880994,  0.3468035 ])

In [433]:
sorted(learn_B[3])[::-1][:10]

[0.86666642560669305,
 0.13333329624718354,
 9.7558467042463064e-08,
 7.8864024947039816e-08,
 7.3768681831593798e-08,
 2.7954713905161562e-08,
 2.3081614696625403e-13,
 4.7646285611213419e-15,
 7.208513291079656e-17,
 1.0133722522339254e-17]

In [431]:
sorted(real_B[0])[::-1][:10]

[0.88648495850517839,
 0.047044318619915884,
 0.045957649035444324,
 0.007183283121060772,
 0.0051530020331418723,
 0.0023709546991718886,
 0.0022970121354764289,
 0.0016303665415172482,
 0.00090000972074400008,
 0.00043614069755062225]